# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 01 Dec 2015 22:06:10 +0000
*	@ALL	0
*	@user	8
sgc:*	google108486582154571123015	16
dms:*	@ALL	1
