<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: Herson Cruz
 * Date: Fri, 03 Mar 2017 14:12:17 -0600
 */

$conf['title'] = 'Document Management System';
$conf['start'] = 'start';
$conf['lang'] = 'es';
$conf['template'] = 'codowik';
$conf['tagline'] = 'Business and Technology Solutions';
$conf['license'] = '';
$conf['useacl'] = 1;
$conf['authtype'] = 'authgoogle';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,profile_delete';
$conf['subscribers'] = 1;
$conf['notify'] = 'wiki@multisistemas.com.sv';
$conf['registernotify'] = 'support@multisistemas.com.sv';
$conf['mailfrom'] = 'wiki@multisistemas.com.sv';
$conf['mailprefix'] = 'Multisistemas Wiki';
$conf['updatecheck'] = 0;
$conf['userewrite'] = '2';
$conf['proxy']['user'] = 'herson';
$conf['proxy']['pass'] = '<b>TTRrITR2M2wwMjAxNA==';
$conf['plugin']['publish']['apr_namespaces'] = 'sgc';
$conf['plugin']['publish']['no_apr_namespaces'] = 'wf';
$conf['plugin']['authgoogle']['allowed_domains'] = '*@multisistemas.com.sv';
$conf['plugin']['authgoogle']['client_id'] = '759994973962-nr1s2n4i57bj13tsovhje7q563g062dq.apps.googleusercontent.com';
$conf['plugin']['authgoogle']['client_secret'] = '1tLGghVX96icj4pscrCaFDg3';
$conf['plugin']['authgoogle']['default_groups'] = 'user';
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['visibilityButton'] = 1;
$conf['plugin']['discussion']['moderatorsnotify'] = 1;
$conf['plugin']['ckgedit']['scayt_lang'] = 'Spanish/es_ES';
$conf['plugin']['ckgedit']['other_lang'] = 'es';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'journal';
$conf['tpl']['bootstrap3']['semantic'] = '1';
$conf['tpl']['bootstrap3']['fluidContainer'] = '1';
$conf['tpl']['monobook']['monobook_userpage'] = '0';
$conf['tpl']['monobook']['monobook_sitenotice_translate'] = '0';
$conf['tpl']['monobook']['monobook_navigation_translate'] = '0';
$conf['tpl']['monobook']['monobook_copyright'] = '0';
$conf['tpl']['monobook']['monobook_copyright_default'] = '0';
$conf['tpl']['monobook']['monobook_copyright_translate'] = '0';
$conf['tpl']['monobook']['monobook_closedwiki'] = '1';

// end auto-generated content
